server:
  port: 8080
spring:
  application:
    name: LiveRankAPI
  datasource:
    url: jdbc:h2:mem:LiveRankDB
    driverClassName: org.h2.Driver
    userName: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true